#!/bin/sh

### BEGIN INIT INFO
# Provides:          githook
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: accepts hooks from gitlab used to deploy code
# Description:       accepts hooks from gitlab used to deploy code
### END INIT INFO

DAEMON="/usr/bin/python /skywatch/githooks/githook.py"
ARGS="8000"
DAEMON_NAME=githook
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid
. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting $DAEMON_NAME daemon"
    start-stop-daemon --start --pidfile $PIDFILE  --user $DAEMON_USER -b --make-pidfile --chuid $DAEMON_USER --exec $DAEMON $ARGS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10 --verbose
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
